/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { ColorScheme } from '../../../../platform/theme/common/theme.js';

/**
 * Contracts for the Primal theme gallery — the browse-and-preview surface for
 * every colour theme the window has, not only the six vibes.
 *
 * The extension bundles twenty-one generated themes; `PRIMAL_VIBES` names six.
 * The other fifteen were invisible to every picker in the product. This module
 * holds the vocabulary the gallery classifies them with, kept separate from the
 * pane so the classification stays pure and testable.
 */

/** The editor pane id, mirroring `PrimalStartEditor.ID`. */
export const PRIMAL_THEME_GALLERY_EDITOR_ID = 'workbench.editor.primalThemeGallery';

/** Opens the gallery. Referenced from the vibe quick pick and the command palette. */
export const PRIMAL_THEME_GALLERY_COMMAND_ID = 'primalCode.themes.gallery';

/** Imports a palette or theme JSON the user pastes in. */
export const PRIMAL_THEME_IMPORT_COMMAND_ID = 'primalCode.themes.import';

/** Removes whatever a previous import wrote to `workbench.colorCustomizations`. */
export const PRIMAL_THEME_CLEAR_IMPORT_COMMAND_ID = 'primalCode.themes.clearImport';

/** The bundled theme extension every Primal theme is contributed by. */
export const PRIMAL_THEME_EXTENSION_ID = 'vscode.theme-primal';

/** The prefix every Primal theme's display name carries. */
export const PRIMAL_THEME_LABEL_PREFIX = 'Primal ';

/**
 * Where a theme came from, which decides what applying it actually does.
 *
 * A `vibe` moves the colour theme, the product icon theme and the file icon
 * theme together. Everything else moves the colour theme alone — the card says
 * so in words, because a user who applies a corpus theme and finds the vibe
 * status bar reading "Custom" is owed an explanation before the fact.
 */
export type PrimalThemeSource =
	/** One of the six vibes in `PRIMAL_VIBES`. */
	| 'vibe'
	/** Generated by this product's theme pipeline but not promoted to a vibe. */
	| 'corpus'
	/** Contributed by any other extension. */
	| 'installed';

/** Light, dark or one of the two high-contrast variants — as a word, never a colour. */
export type PrimalThemeMode = 'light' | 'dark' | 'highContrastLight' | 'highContrastDark';

/** How the grid is grouped. */
export type PrimalThemeGrouping = 'family' | 'mode';

/**
 * The minimum a theme has to tell the gallery about itself.
 *
 * Deliberately narrower than `IWorkbenchColorTheme` so the classification can be
 * unit-tested with plain objects.
 */
export interface IPrimalThemeDescriptor {
	readonly settingsId: string;
	readonly label: string;
	readonly type: ColorScheme;
	/** The contributing extension's identifier, when there is one. */
	readonly extensionId?: string;
}

/** One classified theme, as the grid renders it. */
export interface IPrimalThemeEntry {
	readonly settingsId: string;
	/** The full display name, e.g. `Primal Umber Hard`. */
	readonly label: string;
	/** The short name shown on the card, e.g. `Umber Hard`. */
	readonly shortLabel: string;
	/** The grouping key, e.g. `Umber`. */
	readonly family: string;
	readonly mode: PrimalThemeMode;
	readonly source: PrimalThemeSource;
	/** Set when {@link source} is `vibe`: the id `applyVibe` takes. */
	readonly vibeId?: string;
}

/**
 * The little the catalogue needs to know about a vibe.
 *
 * Structural rather than an import of `IPrimalVibe`: `PRIMAL_VIBES` stays the
 * single vibe list and the gallery reads it, but the classification itself is
 * pure and belongs in `common`, where a `browser`-layer import is not allowed.
 * `IPrimalVibe` satisfies this shape, so the pane hands `PRIMAL_VIBES` straight in.
 */
export interface IPrimalVibeReference {
	readonly id: string;
	/** Settings id of the vibe's colour theme. */
	readonly colorTheme: string;
}

/** True for the two high-contrast schemes, which the gallery labels separately. */
export function isHighContrastScheme(type: ColorScheme): boolean {
	return type === ColorScheme.HIGH_CONTRAST_DARK || type === ColorScheme.HIGH_CONTRAST_LIGHT;
}
